//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmerCar
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_A33B8A_emercarEntities : DbContext
    {
        public DB_A33B8A_emercarEntities()
            : base("name=DB_A33B8A_emercarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accident> Accidents { get; set; }
        public virtual DbSet<Car_Model> Car_Model { get; set; }
        public virtual DbSet<Car_Type> Car_Type { get; set; }
        public virtual DbSet<Mechanical> Mechanicals { get; set; }
        public virtual DbSet<Number> Numbers { get; set; }
        public virtual DbSet<Park> Parks { get; set; }
        public virtual DbSet<UserActivation> UserActivations { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<PasswordReset> PasswordResets { get; set; }
    }
}
