//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmerCar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mechanical
    {
        public int Mechanical_ID { get; set; }
        public string Mechanical_Name { get; set; }
        public string Phone_Number { get; set; }
        public float Location_Lat { get; set; }
        public float Location_Long { get; set; }
        public int Specified_In { get; set; }
    
        public virtual Car_Type Car_Type { get; set; }
    }
}
