//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmerCar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Number
    {
        public int User_ID { get; set; }
        public long Number1 { get; set; }
        public Nullable<long> Number2 { get; set; }
        public Nullable<long> Number3 { get; set; }
        public Nullable<long> Number4 { get; set; }
        public Nullable<long> Number5 { get; set; }
    
        public virtual User User { get; set; }
    }
}
