//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmerCar
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Accidents = new HashSet<Accident>();
            this.Accidents1 = new HashSet<Accident>();
            this.Parks = new HashSet<Park>();
        }
    
        public string Email { get; set; }
        public string UserName { get; set; }
        public string Pass { get; set; }
        public string Car_ID { get; set; }
        public int UserID { get; set; }
        public long User_Number { get; set; }
        public Nullable<int> Car_ModelId { get; set; }
        public bool IsVerified { get; set; }
        public string FireBaseToken { get; set; }
        public byte[] ProfilePicture { get; set; }
        public string Code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accident> Accidents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accident> Accidents1 { get; set; }
        public virtual Car_Model Car_Model { get; set; }
        public virtual Number Number { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Park> Parks { get; set; }
        public virtual UserActivation UserActivation { get; set; }
    }
}
